name: unitycatalog

services:
  pyspark:
    build:
      context: pyspark
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "4040:4040"
      - "8888:8888"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab
    volumes:
      - type: bind
        source: unitycatalog/etc/conf
        target: /opt/delta/etc/conf
      - type: bind
        source: data_warehouse
        target: /home/unitycatalog/etc/data/external
      - type: bind
        source: ./notebooks
        target: /tmp/notebooks
      - type: bind
        source: ./README.md
        target: /tmp/notebooks/README.md
      - type: bind
        source: ./pyspark/startup_spark.py
        target: /opt/startup_spark.py
      - type: bind
        source: ./pyspark/entrypoint.sh
        target: /opt/entrypoint.sh
    entrypoint: ["/bin/bash", "/opt/entrypoint.sh"]
    command: >
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --NotebookApp.token=''
      --NotebookApp.password=''
      --notebook-dir=/tmp/notebooks
      --allow-root
  
  server:
    build:
      context: unitycatalog
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: unitycatalog/etc/conf
        target: /opt/unitycatalog/etc/conf
      - type: volume
        source: unitycatalog
        target: /home/unitycatalog
      - type: bind
        source: data_warehouse
        target: /home/unitycatalog/etc/data/external
  
  ui:
    build:
      context: unitycatalog/ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      MLFLOW_BACKEND_STORE_URI: /mlflow/mlruns
      MLFLOW_ARTIFACT_ROOT: /mlflow/mlruns
    volumes:
      - mlflow_data:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns --host 0.0.0.0

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8082:80"
    volumes:
      - type: bind
        source: ./data_warehouse
        target: /srv/data_warehouse
      - type: bind
        source: ./delta
        target: /srv/delta

volumes:
  # Persist docker volume across container restarts
  unitycatalog:
  mlflow_data:
