name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip=24.0
  - setuptools=69.5.1
  - wheel=0.43.0
  - pyspark=3.5.5
  - pandas=2.1.4
  - numpy=1.26.4
  - pyarrow=16.1.0
  - jupyter=1.1.1
  - jupyterlab=4.4.0
  - ipython=8.26.0
  - ipykernel=6.29.5
  - cryptography=42.0.8
  - mypy=1.11.2
  - pydocstyle=6.3.0
  - requests=2.32.3
  - matplotlib-base=3.8.4
  - bokeh=3.4.1
  - scipy=1.13.1
  - sqlalchemy=2.0.31
  - psycopg2=2.9.9
  - pyyaml=6.0.1
  - jinja2=3.1.4
  - click=8.1.7
  - tqdm=4.66.4
  - joblib=1.4.2
  - dask=2024.6.2
  - fsspec=2024.6.1
  - pytz=2024.1
  - python-dateutil=2.9.0
  - openpyxl=3.1.5
  - xlrd=2.0.1
  - h5py=3.11.0
  - flake8=7.1.0
  - isort=5.13.2
  - pre-commit=3.7.1
  - pip:
    - pytest==8.2.2
    - pytest-cov==5.0.0
    - black==24.4.2
    - delta-spark==3.3.1
    - deltalake==1.0.1
    - twine==5.1.1
    - importlib-metadata==7.2.1
    - databricks-sql-connector==3.2.0
    - great-expectations==0.18.16
    - mlflow==2.13.2
    - pydantic==2.7.4
    - typer==0.12.3
